---
- name: Caminho do binário do tsuru 
  stat: "path=/usr/bin/tsuru"
  register: tsuru_binary

- name: Download do binário tsuru
  shell: curl -fsSL https://packagecloud.io/install/repositories/tsuru/stable/script.deb.sh | sudo bash

- name: Instalação do tsuru client
  become: yes
  apt: 
    name: tsuru-client

- name: Configurar alvo tsuru que existe na Globo
  command: tsuru target-add default --set-current https://tsuru.globoi.com
  when: tsuru_binary.stat.exists == false

- name: verificar listas de alvos
  command: tsuru target-list
  register: get_target_list

- name: verificar listas de alvos
  debug: 
    msg: "Lista de alvos: {{ get_target_list.stdout }}"

- name: instalação de plugins (admtools)
  command: tsuru plugin-install admtools https://raw.githubusercontent.com/tsuru/admtools/master/admtools
  # tsuru admtools -x dev 'ls'
  # tsuru admtools -c globo-ab /

- name: instalação de plugins (healthcheck)
  command: tsuru plugin install hc http://hcaas.cloud.globoi.com/plugin

- name: instalação de plugins (aclfromhell)
  command: tsuru plugin install acl http://aclfromhell.cloud.globoi.com/plugin/darwin/acl

- name: instalação de plugins (rpaas)
  command: tsuru plugin install rpaas http://rpaas-api-fe-cme.cloud.globoi.com/plugin

- name: instalação de plugins (rpaas-admin)
  command: tsuru plugin install rpaas-admin http://rpaas-api-be-cme.cloud.globoi.com/admin/plugin

- name: instalação de plugins (rpaasv2)
  command: tsuru plugin install rpaas http://rpaas-api-fe-cme.cloud.globoi.com/plugin

- name: instalação de plugins (tsuru-deploy-module)
  command: tsuru plugin install deploy https://artifactory.globoi.com/artifactory/generic-local/tsuru-deploy-module/deploy
