--- 
- name: Instalação dos binários pyenv e virtualenv
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: git://github.com/yyuu/pyenv.git
      dest: ~/.pyenv
    - repo: git://github.com/yyuu/pyenv-virtualenv.git
      dest: ~/.pyenv/plugins/pyenv-virtualenv

- name: Exportar as variáveis do pyenv 
  lineinfile:
    path: "{{ path_user }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'

- name: Instalação do python
  become: yes
  shell: /bin/bash -c 'source {{ path_user }}/.bashrc' && {{ path_user }}/.pyenv/bin/pyenv install 3.8.9
